### ISSUE TITLE
Support registration of stream artifacts in squbs modules/cubes

### ISSUE THREAD

**Issue by akara** [paypal/squbs#7] opened 2015-08-08 00:16 UTC
squbs has been supporting registration of actors and services so far. With the arrival of akka-streams in squbs, we need to support registration of stream artifacts. We need to prototype/discuss the proper manifestation of these artifacts before going about implementing it.

**Comment by anilgursel** [comment] 2016-03-07 22:57
Duplicate of #184

**Closed by anilgursel** 2016-03-07 22:57 UTC
Labels: duplicate, enhancement
