### ISSUE TITLE
Move squbs request dispatching from Spray to akka-http

### ISSUE THREAD

**Issue by akara** [paypal/squbs#6] opened 2015-08-08 00:13 UTC
Akka-http 1.1 promises performance on par with Spray and will replace Spray going forward. squbs needs to adopt akka-http as the replacement for spray.

This issue is created to deal with akka-http from the server dispatch side.

**Comment by anilgursel** [comment] 2016-03-07 22:58
Duplicate of #176

**Closed by anilgursel** 2016-03-07 22:58 UTC
Labels: duplicate, enhancement
